# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rswag-api` gem.
# Please instead update this file by running `bin/tapioca gem rswag-api`.

# source://rswag-api//lib/rswag/api/configuration.rb#1
module Rswag; end

# source://rswag-api//lib/rswag/api/configuration.rb#2
module Rswag::Api
  class << self
    # source://rswag-api//lib/rswag/api.rb#10
    def config; end

    # @yield [config]
    #
    # source://rswag-api//lib/rswag/api.rb#6
    def configure; end

    # source://railties/7.0.4/lib/rails/engine.rb#405
    def railtie_helpers_paths; end

    # source://railties/7.0.4/lib/rails/engine.rb#394
    def railtie_namespace; end

    # source://railties/7.0.4/lib/rails/engine.rb#409
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://railties/7.0.4/lib/rails/engine.rb#397
    def table_name_prefix; end

    # source://railties/7.0.4/lib/rails/engine.rb#401
    def use_relative_model_naming?; end
  end
end

# source://rswag-api//lib/rswag/api/configuration.rb#3
class Rswag::Api::Configuration
  # source://rswag-api//lib/rswag/api/configuration.rb#6
  def resolve_swagger_root(env); end

  # Returns the value of attribute swagger_filter.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_filter; end

  # Sets the attribute swagger_filter
  #
  # @param value the value to set the attribute swagger_filter to.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_filter=(_arg0); end

  # Returns the value of attribute swagger_headers.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_headers; end

  # Sets the attribute swagger_headers
  #
  # @param value the value to set the attribute swagger_headers to.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_headers=(_arg0); end

  # Returns the value of attribute swagger_root.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_root; end

  # Sets the attribute swagger_root
  #
  # @param value the value to set the attribute swagger_root to.
  #
  # source://rswag-api//lib/rswag/api/configuration.rb#4
  def swagger_root=(_arg0); end
end

# source://rswag-api//lib/rswag/api/engine.rb#5
class Rswag::Api::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.4/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://rswag-api//lib/rswag/api/middleware.rb#7
class Rswag::Api::Middleware
  # @return [Middleware] a new instance of Middleware
  #
  # source://rswag-api//lib/rswag/api/middleware.rb#9
  def initialize(app, config); end

  # source://rswag-api//lib/rswag/api/middleware.rb#14
  def call(env); end

  private

  # source://rswag-api//lib/rswag/api/middleware.rb#49
  def load_json(filename); end

  # source://rswag-api//lib/rswag/api/middleware.rb#45
  def load_yaml(filename); end

  # source://rswag-api//lib/rswag/api/middleware.rb#37
  def parse_file(filename); end

  # source://rswag-api//lib/rswag/api/middleware.rb#53
  def unload_swagger(filename, swagger); end
end
