# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FastJsonapi::ObjectSerializer`.
# Please instead update this file by running `bin/tapioca dsl FastJsonapi::ObjectSerializer`.

module FastJsonapi::ObjectSerializer
  mixes_in_class_methods ::FastJsonapi::SerializationCore::ClassMethods
end
