services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  pg_data:
