version: "3.4"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3987:3000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - HISTFILE=/usr/src/app/log/.bash_history 
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30