# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Devise::RegistrationsController; end
module Devise::SessionsController; end
module Query::Scopes::NotFoundError; end
module Query::Scopes::Search::Matcher; end
module Query::Scopes::Search::Value; end
