name: CI

# SET THE FOLLOWING VARS FOR REPO ONLY:
# TEST_DB_NAME, IMAGE_NAME

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - ".kubernetes/**"

jobs:
  ci:
    permissions:
      contents: write
    runs-on: [self-hosted, serverina]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ vars.TEST_DB_NAME }}
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Run tests
        run: |
          RAILS_ENV=test DB_PORT=${{ job.services.postgres.ports[5432] }} bundle exec rspec spec

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Store variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "VERSION=$(bundle exec rake version:print)" >> $GITHUB_ENV

      # Do not create the sha extension if it is default branch
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "SHA_EXTENSION=" >> $GITHUB_ENV
      - if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "SHA_EXTENSION=-$SHA_SHORT" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          load: false # set to true if using slim, and set push to false
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.IMAGE_NAME }}:${{ env.VERSION }}${{ env.SHA_EXTENSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Bump version
        run: bundle exec rake version:patch

      # Bump if default branch
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update version"
          add: "VERSION"

      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
        run: |
          gh release create ${{ env.VERSION }} \
              --repo="$GITHUB_REPOSITORY" \
              --title=${{ env.VERSION }} \
              --generate-notes
