apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-name-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{ if eq .Values.env "dev" }}
    db_name: set_dev_name
    {{ else if eq .Values.env "prod" }}
    db_name: set_prod_name
    {{ end }}
  template:
    metadata:
      creationTimestamp: null
      name: db-name-secret
      namespace: {{ .Values.namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{ if eq .Values.env "dev" }}
    password: set_dev_name
    {{ else if eq .Values.env "prod" }}
    password: set_prod_name
    {{ end }}
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: {{ .Values.namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-key-base-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{ if eq .Values.env "dev" }}
    secret_key_base: set_dev_secret_key_base
    {{ else if eq .Values.env "prod" }}
    secret_key_base: set_prod_secret_key_base
    {{ end }}
  template:
    metadata:
      creationTimestamp: null
      name: secret-key-base-secret
      namespace: {{ .Values.namespace }}
